server:
  port: 9192

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/lakeSide-Hotel-DB
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

  servlet:
    multipart:
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB

